güncellenmiş proje/sporMerkezi1/sporMerkezi1/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sporMerkezi1.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult admindex()
        {

            return View();
        }

    }
}

güncellenmiş proje/sporMerkezi1/sporMerkezi1/Areas/Admin/Controllers/GrupKayitController.cs
using sporMerkezi1.DAL;
using sporMerkezi1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sporMerkezi1.Areas.Admin.Controllers
{
    public class GrupKayitController : Controller
    {
        // GET: Admin/GrupKayit
        public ActionResult grupIndex()
        {
            return View();
        }

    }
}

güncellenmiş proje/sporMerkezi1/sporMerkezi1/Areas/Admin/Controllers/KatilimListesiController.cs
using sporMerkezi1.DAL;
using sporMerkezi1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace sporMerkezi1.Areas.Admin.Controllers
{
    public class KatilimListesiController : Controller
    {

        //public ActionResult kListe()
        //{
           
            //    return View(Tuple.Create<UyeKayit, Ders>(new UyeKayit(), new Ders()));
            //    return View();
            //}
            //public ActionResult Model([Bind(Prefix ="item1")]sporMerkezi1.Models.UyeKayit Model1,[Bind(Prefix ="item2")]sporMerkezi1.Models.Ders Model2)
            //{
        //    return View();
        //}


        // GET: Admin/KatilimListesi
        public ActionResult kListe(Ders ders)
        {

            if (ModelState.IsValid)
            {

                var Dersler = new List<Ders>
           {
               new Ders {DersID=200,DersTarihi=DateTime.Parse("19-12-2016"),DersSaati=DateTime.Parse("11:00:00"),DersAdi="Studio Pilates" },
                 new Ders {DersID=201,DersTarihi=DateTime.Parse("19-12-2016"),DersSaati=DateTime.Parse("15:00:00"),DersAdi="Spinning" },
                   new Ders {DersID=202,DersTarihi=DateTime.Parse("20-12-2016"),DersSaati=DateTime.Parse("12:00:00"),DersAdi="Zumba" },
                     new Ders {DersID=203,DersTarihi=DateTime.Parse("20-12-2016"),DersSaati=DateTime.Parse("16:00:00"),DersAdi="Grup Yüzme" },
                       new Ders {DersID=200,DersTarihi=DateTime.Parse("21-12-2016"),DersSaati=DateTime.Parse("11:00:00"),DersAdi="Studio Pilates" },
                       new Ders {DersID=201,DersTarihi=DateTime.Parse("21-12-2016"),DersSaati=DateTime.Parse("15:00:00"),DersAdi="Spinning" },
                         new Ders {DersID=200,DersTarihi=DateTime.Parse("22-12-2016"),DersSaati=DateTime.Parse("14:00:00"),DersAdi="Studio Pilates" },
                         new Ders {DersID=203,DersTarihi=DateTime.Parse("22-12-2016"),DersSaati=DateTime.Parse("18:00:00"),DersAdi="Grup Yüzme" },
                         new Ders {DersID=204,DersTarihi=DateTime.Parse("23-12-2016"),DersSaati=DateTime.Parse("11:00:00"),DersAdi="Abs&Strech" },
                         new Ders {DersID=205,DersTarihi=DateTime.Parse("23-12-2016"),DersSaati=DateTime.Parse("17:00:00"),DersAdi="Le Boxing" },
             };
                var dbContext = new sporContext();
                //s=> dbContext.Dersler.Add(s);
                dbContext.SaveChanges();

                var GrupKayitlar = new List<GrupKayit>
           {
               new GrupKayit {DersID=203,ID=1 },
               new GrupKayit {DersID=200,ID=1 },
               new GrupKayit {DersID=202,ID=2 },
               new GrupKayit {DersID=201,ID=3 }
           };

                //GrupKayitlar.ForEach(s => dbContext.GrupKayitlar.Add(s));
                dbContext.SaveChanges();
                

                return View(dbContext.Dersler.ToList());

            }
            else
            {
                return View();
            }
        }

        
      
    }
}

    

güncellenmiş proje/sporMerkezi1/sporMerkezi1/Areas/Admin/Controllers/YorumController.cs
using sporMerkezi1.Areas.Admin.Models;
using sporMerkezi1.DAL;
using sporMerkezi1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace sporMerkezi1.Areas.Admin.Controllers
{
    public class YorumController : Controller
    {
       
        [HttpGet]
        public ActionResult yorumIndex()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        // GET: Admin/Yorum
        public ActionResult yorumIndex(Yorum Yorums)
        {
            if (ModelState.IsValid)
            {
                var yorum = new Yorum() { Tarih = Yorums.Tarih, Ekle = Yorums.Ekle, };
                var dbContext = new sporContext();
                dbContext.Yorumlar.Add(yorum);
                dbContext.SaveChanges();             
                return RedirectToAction("Index","../Home");
            }

            else
            {
                return View();
            }
        }

    }
}

güncellenmiş proje/sporMerkezi1/sporMerkezi1/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/cssa/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/cssa/sb-admin.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Content/cssa/plugins/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/fonts/cssf/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div id="wrapper" style="background-color:#ffffff">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:#31708f">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"style="color:#ffffff" >Admin Paneli</a>
            </div>
           

           
          
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse" >
                <ul class="nav navbar-nav side-nav" style="background-color:#31708f; color:#ffffff" > 
                    <li class="morris-hover">
                        @Html.ActionLink("Grup Dersleri", "admindex", "AdminHome") 
                    </li>
                    <li>
                        @Html.ActionLink("Ders Tablosu", "grupIndex", "GrupKayit")
                    </li>
                    <li>
                        @Html.ActionLink("Katılım Listesi", "kListe", "KatilimListesi")
                    </li>
                    <li>
                        @Html.ActionLink("Yorum Ekle", "yorumIndex", "Yorum")
                    </li>   
                    <li>
                        @Html.ActionLink("Oturumu Kapat", "Index", "../Home")
                    </li>   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
        @RenderBody();
       
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Scripts/js/plugins/morris/raphael.min.js"></script>
    <script src="~/Scripts/js/plugins/morris/morris.min.js"></script>
    <script src="~/Scripts/js/plugins/morris/morris-data.js"></script>
</body>
</html>